## Import the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Import the dataset

In [5]:
df = pd.read_csv('Data[1].csv')
X = df.iloc[:,:-1].values #df slice not include the last column 
df.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [7]:
y = df.iloc[:,-1].values
#y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

In [8]:
y = y.reshape(len(y),1)
#y

array([[463.26],
       [444.37],
       [488.56],
       ...,
       [429.57],
       [435.74],
       [453.28]])

## Splitting the dataset into the Training and Test set 

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

## Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
X_train = sc_x.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

## Training the SVR model on the Training set

In [11]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train,y_train)

C:\Users\USER\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the Test set results

In [12]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(y_pred)

[[456.83]
 [436.97]
 [434.65]
 ...
 [457.01]
 [472.45]
 [448.9 ]]


## Evaluating the Model Performance

In [13]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.9438810535246882