In [15]:
import numpy as np
rng = np.random.RandomState(1)
X = rng.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X, y)
#X.shape
print(clf.predict(X[2:3]))

[3]


In [17]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import  CategoricalNB
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score, recall_score, precision_score
from sklearn.metrics import f1_score, classification_report
buy=pd.read_csv("buyComputer.csv")
features = buy.columns.tolist()
features.remove('BuyComputer')
buy.head(5)

agelevel  income student     credit BuyComputer
0    young    high      no       fair          no
1    young    high      no  excellent          no
2   middle    high      no       fair         yes
3   senior  medium      no       fair         yes
4   senior     low     yes       fair         yes

In [18]:
encoder1 = OrdinalEncoder()
data_encoded = encoder1.fit_transform(buy[features])
data_encoded

array([[2., 0., 0., 1.],
       [2., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 2., 0., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [2., 2., 0., 1.],
       [2., 1., 1., 1.],
       [1., 2., 1., 1.],
       [2., 2., 1., 0.],
       [0., 2., 0., 0.],
       [0., 0., 1., 1.],
       [1., 2., 0., 0.]])

In [19]:
buy_encoded = pd.DataFrame(data_encoded, columns=features)

encoder2 = LabelEncoder()
target_encoded = encoder2.fit_transform(buy['BuyComputer'])
#buy_encoded['Class'] = target_encoded
#data_encoded
target_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [20]:
X_train= buy_encoded
y_train= target_encoded
clf = CategoricalNB()
clf.fit(X_train, y_train)

train_score = clf.score(X_train, y_train)
print(train_score)

0.9285714285714286


In [23]:
#%% preparing X_test
buy1=pd.read_csv("buyComputer1.csv")
features = buy1.columns.tolist()
features.remove('BuyComputer')
# note that only transform no fit in the following code
data_encoded = encoder1.transform(buy1[features])
X_test = pd.DataFrame(data_encoded, columns=features)
clf.predict(X_test)
#buy1

array([1])