In [2]:
#import os
#os.chdir('G:\\aibd\Python')
# numpy operations
import numpy as np
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
b=np.array([[1,2], [3,4], [5,6]])
b.ndim     # dimension of array

2

In [5]:
b.shape    # shape of array

(3, 2)

In [9]:
np.ones((3,3))   # fill in 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((3,6))  # fill in 0

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.eye(4)        # unit matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.random.randn(6,4)   # random number generator, normal dist.

array([[ 0.90918244, -0.22714291,  0.21907727,  1.3407964 ],
       [-0.10855913, -0.06586494,  0.82939993, -0.58146178],
       [ 0.04574256, -0.98400865,  0.08096114, -1.35986575],
       [ 1.14071943, -1.85111367,  0.51995639, -0.28317827],
       [ 1.55587828,  0.56824535,  0.10532914,  1.41381496],
       [-0.10139255, -0.24204238,  0.34154561,  0.88989919]])

In [ ]:
a=np.arange(10)    

In [ ]:
a[0], a[3], a[-1]     # index

In [ ]:
a[:4]     # from begining to 4 (not include 4)

In [ ]:
a[3:7]    # open at the right end

In [ ]:
a[6:]

In [ ]:
a[2:8:2]  # 2 to 8 step by 2

In [ ]:
a[2::2]   # 2 to last step by 2

In [ ]:
a[::3]    # step by 3

In [13]:
# index in a 2-d array
a= np.arange(0,51,10).reshape(6,1) +np.arange(6)   # interesting example!
a[0, 0], a[2, -1]

(0, 25)

In [ ]:
a[0, 2:5]

In [ ]:
a[:3, 3:]

In [ ]:
a[2, :]

In [ ]:
a[2,:].shape  # transformed to column vector

In [ ]:
a[:, 3].shape # column vector

In [ ]:
a[:, ::2]

In [ ]:
a[::2, ::3]

In [ ]:
# indexed by boolean array
a=np.random.randint(10,20,6)  # 6 integer rand. number from 10 to 20
a % 2 ==0

In [ ]:
a[a % 2 ==0]

In [ ]:
# Numpy tends to arange array into column vector
a=np.arange(0,51, 10).reshape(6,1) + np.arange(6)
a[a % 2 ==0].shape

In [ ]:
b=a[a % 2 ==0]
b[3]     # check index

In [ ]:
# Numpy share memory
a=np.arange(6)
b=a[2:5]

In [ ]:
b[1] = 100    # check a and b

In [ ]:
np.may_share_memory(a,b)
b=a[2:6].copy()

In [ ]:
b[1]=3    # both don't share memory