# 5.1	Construct Computational Graph

# import tensorflow package

In [1]:
import tensorflow.compat.v1 as tf
#session_config.graph_options.rewrite_options.disable_meta_optimizer = True
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as session :
  result = session.run(add)
  print(result)

# construct const 

In [22]:
ts_c = tf.constant(2,name='ts_c')

In [ ]:
ts_c

# construct Variable

In [23]:
ts_x = tf.Variable(ts_c+5,name='ts_x')

In [ ]:
ts_x

# 5.2	Construct Session to execute Computational Graph

In [24]:
sess=tf.compat.v1.Session()

In [25]:
#tf.compat.v1.global_variables_initializer()
#sess.run(init)
tf.compat.v1.initialize_all_variables 

<function tensorflow.python.ops.variables.initialize_all_variables()>

In [6]:
print('ts_c=',sess.run(ts_c))

ts_c= 2


In [28]:
ts_x = tf.Variable(ts_c+5,name='ts_x')

In [26]:
print('ts_c=',ts_c.eval(session=sess))

ts_c= 2


In [30]:
print('ts_x=',ts_x.eval(session=sess))

In [32]:
#sess.close()    

# Session open close

In [31]:
import tensorflow.compat.v1 as tf
#import tensorflow as tf
ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')

sess=tf.compat.v1.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('ts_c=',sess.run(ts_c))
print('ts_x=',sess.run(ts_x))
sess.close()

ts_c= 2
ts_x= 7


# Using With to start a Session

In [33]:
import tensorflow.compat.v1 as tf
ts_c = tf.constant(2,name='ts_c')
ts_x = tf.Variable(ts_c+5,name='ts_x')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c=',sess.run(ts_c))
    print('ts_x=',sess.run(ts_x))

ts_c= 2
ts_x= 7


# 4.placeholder: hold data only available when executing

In [34]:
width = tf.placeholder("int32")
height = tf.placeholder("int32")
area=tf.multiply(width,height)

In [35]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=',sess.run(area,feed_dict={width: 6, height: 8}))

area= 48


# Create dim  1 tensor

In [36]:
ts_X = tf.Variable([0.4,0.2,0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [37]:
print(X.shape)

(3,)


# Create dim  2 tensor

In [38]:
ts_X = tf.Variable([[0.4,0.2,0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X=sess.run(ts_X)
    print(X)   

[[0.4 0.2 0.4]]


In [39]:
print('shape:',X.shape)

shape: (1, 3)


In [40]:
W = tf.Variable([[-0.5,-0.2 ],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array=sess.run(W)
    print(W_array)   
                        

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [ ]:
print(W_array.shape)

# matmul 

In [41]:
X = tf.Variable([[1.,1.,1.]])

W = tf.Variable([[-0.5,-0.2 ],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])
                        
XW =tf.matmul(X,W )
                       
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW ))

[[-1.3  0.4]]


# tf.add

In [42]:
b = tf.Variable([[ 0.1,0.2]])
XW =tf.Variable([[-1.3,0.4]])

Sum =XW+b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')    
    print(sess.run(Sum ))

Sum:
[[-1.1999999  0.6      ]]


# Y=X*W+b

In [43]:
X = tf.Variable([[1.,1.,1.]])

W = tf.Variable([[-0.5,-0.2 ],
                 [-0.3, 0.4 ],
                 [-0.5, 0.2 ]])
                         

b = tf.Variable([[0.1,0.2]])
    
XWb =tf.matmul(X,W)+b


with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb:')    
    print(sess.run(XWb ))

XWb:
[[-1.1999999  0.6      ]]
